---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.raw: apt-get update
      changed_when: false

    - name: Install python3, sudo, and passwd
      ansible.builtin.raw: apt-get install -y python3 sudo passwd
      changed_when: true
